name: "Design Ruler"
options:
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

packages:
  DesignRuler:
    path: ../swift/DesignRuler

targets:
  "Design Ruler":
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    dependencies:
      - package: DesignRuler
        product: DesignRulerCore
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: Design Ruler
        CFBundleDisplayName: Design Ruler
        LSUIElement: true
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
        NSApplicationSupportsSecureRestorableState: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cv.haythem.designruler
        PRODUCT_NAME: "Design Ruler"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ARCHS: "$(ARCHS_STANDARD)"
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
