name: "Design Ruler"
options:
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

packages:
  DesignRuler:
    path: ../swift/DesignRuler
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.4.0"

targets:
  "Design Ruler":
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    dependencies:
      - package: DesignRuler
        product: DesignRulerCore
      - package: Sparkle
      - package: KeyboardShortcuts
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: Design Ruler
        CFBundleDisplayName: Design Ruler
        LSUIElement: true
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
        NSApplicationSupportsSecureRestorableState: true
        SUFeedURL: "https://github.com/haythemgataa/design-ruler/releases/latest/download/appcast.xml"
        SUPublicEDKey: "nQlHBasrae63Ai7buw0NQAWV7wMXI70LCFLFbnULImw="
        SUEnableAutomaticChecks: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cv.haythem.designruler
        PRODUCT_NAME: "Design Ruler"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ARCHS: "$(ARCHS_STANDARD)"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Sources/DesignRuler.entitlements
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_IDENTITY: "Developer ID Application"
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
